version: '3'
services:
  bm_service:
    image: registry.cn-hangzhou.aliyuncs.com/pettyfox/pwd-service:${SERVICE_VERSION}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    environment:
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_RECEIVE_LIST: ${MAIL_RECEIVE_LIST}
      RSA_PRIVATE: ${RSA_PRIVATE}
      RSA_PUBLIC: ${RSA_PUBLIC}
    ports:
      - 8090:8080/tcp