version: '3'
services:
  bm_service:
    image: registry.cn-hangzhou.aliyuncs.com/pettyfox/pwd-service:${SERVICE_VERSION}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    environment:
      MAIL_USERNAME:
      MAIL_PASSWORD:
      MAIL_RECEIVE_LIST:
      RSA_PRIVATE:
      OSS_PRIVATE_KEY_SECRET:
      OSS_PRIVATE_KEY_BUCKET:
      OSS_PRIVATE_REGION:
      OSS_PUBLIC_KEY_ID:
      OSS_PUBLIC_KEY_SECRET:
      OSS_PUBLIC_BUCKET:
      OSS_PUBLIC_REGION:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME:
      RABBITMQ_PASSWORD:
      RABBITMQ_NODE_HOST:
      RABBITMQ_NODE_PORT:
      RABBITMQ_VIRTUAL_HOST:
      DNS_APP_ID:
      DNS_APP_PASSWORD:
      NODE_DEFAULT_DOMAIN:
    ports:
      - 7453:8080/tcp